export default [{
    id: "1",
    tag1: "WebDev",
    tag2: "100% Live teaching",
    tag3: "Free",
    title: "JavaScript Essentials Zero to Hero Program (FREE)",
    description: "If there's one thing that never gets old, it's rock-solid JavaScript fundamentals. A strong understanding of JavaScript is essential for having a successful career, no matter which framework you use - React.JS, Vue.JS, Angular & Etc",
    date: "24th January 2022",
    time: "6:30 PM to 7:30 PM IST",
    projects: "3+ Projects & Assignment",
    projectDesc: "Build Projects to understand JavaScript end to end",
    video: "https://player.vimeo.com/video/655825170?h=50860e7dbc"
}, {
    id: "2",
    tag1: "1:1 Personal mentoring",
    tag2: "100% LIVE",
    tag3: "FullStack",
    title: "FullStack Web Development Program (PGP FS)",
    description: "One of the best WebApps we use right now in our daily life is based on MERN or VUE JS, so this program helps you crack that",
    date: "29th January 2022",
    time: "Commitment of 7-10 hours a week",
    projects: "15+ Projects to Build",
    projectDesc: "Food delivery, Cab Booking",
    video: "https://player.vimeo.com/video/655825170?h=50860e7dbc"
}, {
    id: "3",
    tag1: "FullStack",
    tag2: "100% Live",
    tag3: "1:1 Personal Marketing",
    title: "FullStack Data Science Program (PGP FS)",
    description: "From listening about Data Science to being one Data Science Professional with a program so beautifully designed to make you master Data Science",
    date: "24th January 2022",
    time: "Commitment of 6-10 Hours a Week",
    projects: "3+ Projects & Assignment",
    projectDesc: "Build Projects to understand JavaScript end to end",
    video: "https://player.vimeo.com/video/655825170?h=50860e7dbc"
}, {
    id: "4",
    tag1: "3 WebDev",
    tag2: "40% Live teaching",
    tagt3: "",
    title: "JavaScript Essentials Zero to Hero Program (FREE)",
    description: "If there's one thing that never gets old, it's rock-solid JavaScript fundamentals. A strong understanding of JavaScript is essential for having a successful career, no matter which framework you use - React.JS, Vue.JS, Angular & Etc",
    date: "24th January 2022",
    time: "6:30 PM to 7:30 PM IST",
    projects: "3+ Projects & Assignment",
    projectDesc: "Build Projects to understand JavaScript end to end",
    video: "https://player.vimeo.com/video/655825170?h=50860e7dbc"
},{
    id: "5",
    tag1: "Let's learn",
    tag2: "50% Live teaching",
    tatg3: "",
    title: "JavaScript Essentials Zero to Hero Program (FREE)",
    description: "If there's one thing that never gets old, it's rock-solid JavaScript fundamentals. A strong understanding of JavaScript is essential for having a successful career, no matter which framework you use - React.JS, Vue.JS, Angular & Etc",
    date: "24th January 2022",
    time: "6:30 PM to 7:30 PM IST",
    projects: "3+ Projects & Assignment",
    projectDesc: "Build Projects to understand JavaScript end to end",
    video: "https://player.vimeo.com/video/655825170?h=50860e7dbc"
},{
    id: "6",
    tag1: "WeDev",
    tag2: "60% Live teaching",
    tag3: "Free",
    title: "JavaScript Essentials Zero to Hero Program (FREE)",
    description: "If there's one thing that never gets old, it's rock-solid JavaScript fundamentals. A strong understanding of JavaScript is essential for having a successful career, no matter which framework you use - React.JS, Vue.JS, Angular & Etc",
    date: "24th January 2022",
    time: "6:30 PM to 7:30 PM IST",
    projects: "3+ Projects & Assignment",
    projectDesc: "Build Projects to understand JavaScript end to end",
    video: "https://player.vimeo.com/video/655825170?h=50860e7dbc"
},{
    id: "7",
    tag1: "Machine Learning",
    tag2: "70% Live teaching",
    tag3: "Costly",
    title: "JavaScript Essentials Zero to Hero Program (FREE)",
    description: "If there's one thing that never gets old, it's rock-solid JavaScript fundamentals. A strong understanding of JavaScript is essential for having a successful career, no matter which framework you use - React.JS, Vue.JS, Angular & Etc",
    date: "24th January 2022",
    time: "6:30 PM to 7:30 PM IST",
    projects: "3+ Projects & Assignment",
    projectDesc: "Build Projects to understand JavaScript end to end",
    video: "https://player.vimeo.com/video/655825170?h=50860e7dbc"
},{
    id: "8",
    tag1: "Algo & DS",
    tag2: "80% Live teaching",
    tag3: "Heavy",
    title: "JavaScript Essentials Zero to Hero Program (FREE)",
    description: "If there's one thing that never gets old, it's rock-solid JavaScript fundamentals. A strong understanding of JavaScript is essential for having a successful career, no matter which framework you use - React.JS, Vue.JS, Angular & Etc",
    date: "24th January 2022",
    time: "6:30 PM to 7:30 PM IST",
    projects: "3+ Projects & Assignment",
    projectDesc: "Build Projects to understand JavaScript end to end",
    video: "https://player.vimeo.com/video/655825170?h=50860e7dbc"
},{
    id: "9",
    tag1: "AI",
    tag2: "90% Live teaching",
    title: "JavaScript Essentials Zero to Hero Program (FREE)",
    description: "If there's one thing that never gets old, it's rock-solid JavaScript fundamentals. A strong understanding of JavaScript is essential for having a successful career, no matter which framework you use - React.JS, Vue.JS, Angular & Etc",
    date: "24th January 2022",
    time: "6:30 PM to 7:30 PM IST",
    projects: "3+ Projects & Assignment",
    projectDesc: "Build Projects to understand JavaScript end to end",
    video: "https://player.vimeo.com/video/655825170?h=50860e7dbc"
}, ]